Repository planetarium/9c-launcher, pull requests merged in 2022-09, with the labels that each got.

#1876 Bump
  src/v2/resources/collection/icon-action-power.webp
  src/v2/resources/collection/items/crystal.png
  src/v2/utils/monsterCollection/systemRewards.ts
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1885 Fix IPC event name mismatch on updateMachine
  src/v2/machines/updateMachine.ts
Labels: Extra Small

#1898 [Fix] Delete relaunch after player update
  src/main/update/launcher-update.ts
Labels: Extra Small

#1886 Set fallback locale for launching game
  src/stores/game.ts
Labels: Extra Small

#1901 RC-v100291 to main
  src/main/update/launcher-update.ts
Labels: Extra Small

#1887 Register `ninechronicles-launcher` protocol
  src/global.d.ts
  src/main/main.ts
  src/v2/App.tsx
  src/v2/components/core/Menu/index.tsx
  src/v2/ipcTokens.ts
  src/v2/utils/ipc.ts
  src/v2/utils/useExternalURL.tsx
Labels: Medium

#1868 [Refactor] Separate update check
  src/config.ts
  src/interfaces/apv.ts
  src/interfaces/config.ts
  src/main/main.ts
  src/main/update/check.ts
  src/main/update/launcher-update.ts
  src/main/update/player-update.ts
  src/main/update/update.ts
  src/main/update/util.ts
  src/renderer/App.tsx
  src/renderer/DifferentAppProtocolVersionSubscriptionProvider.tsx
  src/utils/apv.ts
  src/utils/url.ts
  src/v2/utils/APVSubscriptionProvider.tsx
  src/v2/utils/apolloClient.ts
Labels: Extra Large

#1851 Fix Visibility Button shown on tab-focused.
  src/v2/components/ui/TextField.tsx
Labels: bug, Extra Small

#1916 [Feature] player, launcher manual update
  src/main/main.ts
  src/main/update/launcher-update.ts
  src/main/update/player-update.ts
  src/main/update/update.ts
  src/v2/views/SettingsOverlay/index.tsx
Labels: Extra Small

#1918 Fix e2e test by update transfer_asset version
  __tests__/fixture/tx_transfer_asset.txt
Labels: Extra Small

#1919 Add onboarding-portal url config
  src/interfaces/config.ts
  src/stores/game.ts
Labels: Extra Small

#1917 [Feature] Handling project version
  src/config.ts
  src/interfaces/apv.ts
  src/interfaces/metadata.ts
  src/main/headless/apv.ts
  src/main/main.ts
  src/main/update/check.ts
  src/main/update/launcher-update.ts
  src/main/update/player-update.ts
  src/main/update/update.ts
  src/main/update/util.ts
  src/utils/apv.ts
  src/utils/url.ts
Labels: Large

#1925 Development to rc v100300
  src/config.ts
  src/interfaces/apv.ts
  src/interfaces/metadata.ts
  src/main/headless/apv.ts
  src/main/main.ts
  src/main/update/check.ts
  src/main/update/launcher-update.ts
  src/main/update/player-update.ts
  src/main/update/update.ts
  src/main/update/util.ts
  src/utils/apv.ts
  src/utils/url.ts
Labels: Large

#1926 [Fix] AnalyzeApvExtra type bug
  src/main/update/check.ts
Labels: Extra Small

#1930 Fix clear cache event to be fired
  src/v2/views/ErrorView/index.tsx
Labels: Extra Small

#1927 Make direct state change while both player update and launcher update required
  src/main/update/player-update.ts
  src/v2/machines/updateMachine.ts
Labels: bug, Extra Small

#1932 Make V1 UpdateView Compatible to Current Updater
  src/renderer/DifferentAppProtocolVersionSubscriptionProvider.tsx
  src/renderer/views/update/UpdateView.tsx
Labels: enhancement, Extra Small

#1933 Ran Lint
  src/renderer/views/update/UpdateView.tsx
Labels: Extra Small

#1938 Hotfix/handle update error
  src/main/main.ts
  src/v2/utils/APVSubscriptionProvider.tsx
  src/v2/utils/useEncounteredAPV.ts
Labels: Small

#1939 Ignore already encountered peer
  src/v2/utils/useEncounteredAPV.ts
Labels: Extra Small

#1944 fix mac game path
  src/config.ts
Labels: Extra Small
