Repository planetarium/9c-launcher, pull requests merged in 2022-08, with the labels that each got.

#1710 Replace react-hot-loader with react-refresh
  package.json
  src/renderer/Root.tsx
  src/v2/App.tsx
  webpack.config.js
  yarn.lock
Labels: Extra Small

#1709 Add WNCG Staking button
  src/v2/components/core/Menu/MenuItem.tsx
  src/v2/components/core/Menu/index.tsx
  src/v2/resources/icons/exchange.png
Labels: Extra Small

#1557 Add mixpanel function
  src/v2/components/core/Layout/UserInfo/index.tsx
  src/v2/utils/mixpanel.ts
  src/v2/utils/usePreload.ts
  src/v2/views/LoginView/index.tsx
  src/v2/views/MonsterCollectionOverlay/index.tsx
  src/v2/views/RegisterView/index.tsx
Labels: Extra Small

#1711 Chore/circleci cross build
  .circleci/config.yml
  Dockerfile.build
  package.json
  scripts/configure-artifact.sh
  scripts/downloadPlayer.ts
  scripts/electron-pack-linux.sh
  scripts/electron-pack.ps1
  scripts/electron-pack.sh
  yarn.lock
Labels: Large

#1718 Fix styles regression from #1709
  src/v2/components/core/Menu/index.tsx
Labels: Extra Small

#1717 Prefer NODE_ENV if defined in Storybook
  .storybook/main.js
Labels: Extra Small

#1720 Make react errors not draggable
  src/v2/global.scss
Labels: Extra Small

#1724 Replace new-window event with setWindowOpenHandler
  src/main/v2/application.ts
Labels: Extra Small

#1725 Some improvements to E2E tests
  .circleci/config.yml
  __tests__/main.spec.ts
Labels: Extra Small

#1716 Bump Electron to 20
  package.json
  webpack.config.js
  yarn.lock
Labels: Extra Small

#1722 Add missing arena rewards
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1728 Make StatusBar shorter
  src/v2/components/core/Layout/StatusBar.tsx
Labels: Extra Small

#1727 [Feature] 9c Player Download & Update
  src/config.ts
  src/main/main.ts
  src/main/update/launcher-update.ts
  src/main/update/player-update.ts
  src/renderer/App.tsx
  src/renderer/DifferentAppProtocolVersionSubscriptionProvider.tsx
  src/v2/machines/updatePlayerMachine.ts
  src/v2/utils/apolloClient.ts
Labels: Medium

#1741 Dedupe dependencies
  src/main/main.ts
  src/renderer/DifferentAppProtocolVersionSubscriptionProvider.tsx
  src/renderer/IntroView.tsx
  src/renderer/components/AccountInfo/AccountInfo.tsx
  src/renderer/components/AccountInfo/AccountInfoContainer.tsx
  src/renderer/components/RetypePasswordForm.tsx
  src/renderer/views/account/CopyCreatedPrivateKeyView.tsx
  src/renderer/views/account/CreateAccountView.tsx
  src/renderer/views/config/ConfigurationView.tsx
  src/renderer/views/lobby/LobbyView.tsx
  src/renderer/views/login/LoginView.tsx
  src/renderer/views/preload/PreloadProgressView.tsx
  src/transfer/stores/headless.ts
  src/v2/Routes.tsx
  src/v2/components/core/Layout/UserInfo/index.tsx
  src/v2/components/ui/Button.stories.tsx
  src/v2/components/ui/FileChooser.tsx
  src/v2/utils/APVSubscriptionProvider.tsx
  src/v2/utils/monsterCollection/index.ts
  src/v2/utils/usePreload.ts
  src/v2/utils/useTx.ts
  src/v2/views/ClaimCollectionRewardsOverlay/ClaimContent.tsx
  src/v2/views/LobbyView/index.tsx
  src/v2/views/MissingActivationView.tsx
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/index.tsx
  src/v2/views/RegisterView/index.tsx
  src/v2/views/SettingsOverlay/FolderChooser.tsx
  yarn.lock
Labels: Large

#1743 Handle case where locale is unset
  src/renderer/i18n/index.tsx
Labels: Extra Small

#1742 Ignore errors on removing useless stores
  src/main/snapshot.ts
Labels: Extra Small

#1738 [Refactor] Doesn't import downloadUrl from apv extra data
  src/config.ts
  src/main/update/launcher-update.ts
  src/main/update/util.ts
Labels: Small

#1736 Install lefthook
  lefthook.yml
  package.json
  yarn.lock
Labels: Extra Small

#1747 Add download-config script
  package.json
Labels: Extra Small

#1745 [Chore] Remove bundle player - CI
  .circleci/config.yml
Labels: Extra Small

#1739 Add PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD to CI install
  .circleci/config.yml
Labels: Extra Small

#1761 [Chore] Fix linux execute path
  src/config.ts
  src/main/main.ts
Labels: Extra Small

#1764 [Chore] Add DownloadBaseURL config
  src/config.ts
  src/interfaces/config.ts
  src/main/main.ts
  src/main/update/util.ts
Labels: Extra Small

#1767 [Feature] Add init player [temp]
  src/config.ts
  src/main/main.ts
  src/main/update/launcher-update.ts
  src/main/update/player-update-temp.ts
Labels: Medium

#1766 chore: remove unused devDependencies and dependencies
  package.json
  src/v2/views/MonsterCollectionOverlay/Migration.tsx
  yarn.lock
Labels: Extra Small

#1777 [Fix] player path include network info
  src/config.ts
  src/main/update/launcher-update.ts
  src/main/update/player-update-temp.ts
  src/main/update/player-update.ts
  src/main/update/util.ts
  src/utils.ts
Labels: Medium

#1778 [Fix] Unlink downloaded file
  src/main/update/player-update-temp.ts
  src/main/update/player-update.ts
Labels: Extra Small

#1780 Drop Corepack
  .circleci/config.yml
Labels: Extra Small

#1784 [Feature] Cleanup old player
  src/main/update/player-update-temp.ts
  src/main/update/util.ts
Labels: Extra Small

#1790 [Fix] File related bugs
  src/main/update/player-update.ts
  src/main/update/util.ts
Labels: Extra Small

#1792 [Fix] playerPath format
  src/config.ts
  src/main/update/player-update-temp.ts
Labels: Extra Small

#1751 Made OverlayBase Scrollable
  src/v2/components/core/OverlayBase/index.tsx
  src/v2/views/SettingsOverlay/index.tsx
Labels: enhancement, Large

#1818 Fix tsc pre-commit hook command
  lefthook.yml
Labels: Extra Small

#1817 Get rid of symlinks
  src/interfaces/store.ts
  src/renderer/App.tsx
  src/renderer/components/AccountInfo/AccountInfo.stories.tsx
  src/renderer/components/Select.tsx
  src/renderer/views/account/CopyCreatedPrivateKeyView.tsx
  src/renderer/views/account/CreateAccountView.tsx
  src/renderer/views/account/RevokeAccountView.tsx
  src/renderer/views/account/reset/ResetPasswordView.tsx
  src/renderer/views/account/reset/ReviewPrivateKeyView.tsx
  src/stores/account.ts
  src/stores/game.ts
  src/stores/standaloneStore.ts
  src/v2/i18n
  src/v2/i18n.ts
  src/v2/stores
  src/v2/utils/useStore.tsx
Labels: Extra Small

#1830 Fixing outdated README.md
  README.ko.md
  README.md
Labels: documentation, enhancement, Small

#1831 Fix missing semicolon in snapshot.ts
  src/main/snapshot.ts
Labels: No Changes

#1828 Merged `src/errors` in `src/main/exceptions`
  src/main/exceptions/FetchError.ts
  src/main/exceptions/HeadlessExitedError.ts
  src/main/exceptions/HeadlessInitializeError.ts
  src/main/exceptions/UndefinedProtectedPrivateKeyError.ts
  src/main/exceptions/index.ts
  src/main/headless/headless.ts
  src/main/main.ts
Labels: Extra Small

#1832 [Chore] Restore e2e test
  __tests__/fixture/config.json
  src/config.ts
  src/interfaces/config.ts
  src/main/snapshot.ts
  src/main/update/launcher-update.ts
Labels: Extra Small

#1833 Fixed getMessage function
  src/v2/views/UpdateView/index.tsx
Labels: bug, Extra Large

#1835 Put Back Linux Support
  src/main/update/launcher-update.ts
  src/main/update/player-update-temp.ts
  src/main/update/player-update.ts
  src/main/update/util.ts
Labels: duplicate, Extra Small

#1837 Fix Chromatic
  .storybook/main.js
  .storybook/preview.js
  src/v2/views/MonsterCollectionOverlay/index.stories.tsx
Labels: Small

#1834 Fixed state on player-update-temp
  src/main/update/player-update-temp.ts
Labels: Extra Small

#1841 [Chore] delete useless import
  src/main/update/launcher-update.ts
Labels: Extra Small

#1776 Dedupe dependencies
  yarn.lock
Labels: No Changes

#1842 Add @Akamig to auto_assign
  .github/auto_assign.yml
Labels: Extra Small

#1844 Update CONTRIBUTING.md
  CONTRIBUTING.md
  package.json
Labels: Extra Small

#1843 Use build-headless command for cache in E2E
  .circleci/config.yml
Labels: Extra Small

#1848 Fix restarting headless failure
  src/main/headless/headless.ts
Labels: Extra Small

#1731 [Feature] Separate download & update player from launcher update
  .circleci/config.yml
  __tests__/fixture/config.json
  src/config.ts
  src/interfaces/config.ts
  src/main/main.ts
  src/main/update/launcher-update.ts
  src/main/update/player-update.ts
  src/main/update/util.ts
  src/renderer/App.tsx
  src/renderer/DifferentAppProtocolVersionSubscriptionProvider.tsx
  src/utils.ts
  src/v2/machines/updateMachine.ts
  src/v2/utils/APVSubscriptionProvider.tsx
  src/v2/utils/apolloClient.ts
  src/v2/views/UpdateView/index.tsx
Labels: Extra Large, separation

#1864 [Fix] Rollback filename
  src/config.ts
  src/main/update/util.ts
Labels: Extra Small

#1865 Update collection stats
  src/v2/resources/collection/icon-action-power.webp
  src/v2/resources/collection/items/crystal.png
  src/v2/utils/monsterCollection/systemRewards.ts
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small
