Repository planetarium/9c-launcher, pull requests merged in 2022-01, with the labels that each got.

#1140 ci(circleci): stop uploading staled s3 artifact
  .circleci/config.yml
Labels: ci

#1168 Add CONTRIBUTING.md
  CONTRIBUTING.ko.md
  CONTRIBUTING.md
Labels: Small

#1175 Add configuration ui for log size
  package.json
  src/interfaces/event.ts
  src/renderer/views/config/ConfigurationView.tsx
  yarn.lock
Labels: Extra Small

#1174 Prevent double submitting on Send NCG screen
  src/transfer/pages/transfer/transfer.tsx
Labels: Extra Small

#1177 Add description about git submodle download and skip build unity player
  CONTRIBUTING.ko.md
  CONTRIBUTING.md
  README.ko.md
  README.md
Labels: Extra Small

#1180 Fix electron target settings
  webpack.config.js
Labels: Extra Small

#1181 Fix Quit Launcher to work without Mixpanel
  src/main/main.ts
Labels: Extra Small

#1186 Show RPC hostname on info pane
  src/renderer/views/layout/Layout.tsx
Labels: Extra Small

#1188 Mask passphrase when logging
  src/main/headless/subcommand.ts
Labels: Extra Small
