Repository planetarium/9c-launcher, pull requests merged in 2022-10, with the labels that each got.

#1945 add download link in error page
  src/config.ts
  src/v2/views/ErrorView/index.tsx
Labels: Extra Small

#1951 Add basic error mechanism to useActivation
  src/api.graphql
  src/v2/utils/useActivation.ts
  src/v2/views/LobbyView/index.tsx
Labels: Extra Small

#1955 Check node tip when selecting an RPC node
  src/api.graphql
  src/config.ts
  src/interfaces/config.ts
Labels: Extra Small

#1570 Implement difference viewer on collection
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/reward.tsx
Labels: Medium

#1965 Revert "Implement difference viewer on collection"
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/reward.tsx
Labels: Medium

#1966 Feat/collection reward diff
  package.json
  src/renderer/DifferentAppProtocolVersionSubscriptionProvider.tsx
  src/renderer/IntroView.tsx
  src/renderer/views/login/LoginView.tsx
  src/v2/Routes.tsx
  src/v2/utils/monsterCollection/systemRewards.ts
  src/v2/utils/useTx.ts
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/reward.tsx
  yarn.lock
Labels: duplicate, enhancement, Large
