Repository planetarium/9c-launcher, pull requests merged in 2022-05, with the labels that each got.

#1399 Use native controls on macos
  src/main/v2/application.ts
  src/v2/components/core/Layout/index.tsx
Labels: Extra Small

#1430 Add chromatic
  .circleci/config.yml
  package.json
  yarn.lock
Labels: Extra Small

#1432 Ignore collection pages with APNG on Chromatic
  src/collection/components/CollectionItem/CollectionItem.stories.tsx
  src/collection/components/LoadingDialog/LoadingDialog.stories.tsx
  src/collection/pages/main/main.stories.tsx
Labels: Extra Small

#1433 Ignore collection pages with APNG on Chromatic
  src/collection/components/CollectionItem/CollectionItem.stories.tsx
  src/collection/components/LoadingDialog/LoadingDialog.stories.tsx
  src/collection/pages/main/main.stories.tsx
Labels: Extra Small

#1410 Monster Collection Revamping
  package.json
  src/api.graphql
  src/main/headless/action.ts
  src/main/headless/headless.ts
  src/schema.graphql
  src/v2/components/core/Layout/UserInfo/index.tsx
  src/v2/components/ui/BareInput.tsx
  src/v2/render.tsx
  src/v2/resources/collection/bg.png
  src/v2/resources/collection/button-activation-hover.png
  src/v2/resources/collection/button-activation-over.png
  src/v2/resources/collection/button-activation.png
  src/v2/resources/collection/button-cancel-2-over.png
  src/v2/resources/collection/button-cancel-2.png
  src/v2/resources/collection/button-cancel-over.png
  src/v2/resources/collection/button-cancel.png
  src/v2/resources/collection/button-inactive.png
  src/v2/resources/collection/button-ok-over.png
  src/v2/resources/collection/button-ok.png
  src/v2/resources/collection/current-status-leaf.png
  src/v2/resources/collection/current-status-round.png
  src/v2/resources/collection/dark-text-bg.png
  src/v2/resources/collection/deposit-bg.png
  src/v2/resources/collection/dot.png
  src/v2/resources/collection/icon-step.png
  src/v2/resources/collection/item-bg.png
  src/v2/resources/collection/items/ncg.png
  src/v2/resources/collection/mark-information.png
  src/v2/resources/collection/monster-1.png
  src/v2/resources/collection/monster-2.png
  src/v2/resources/collection/monster-3.png
  src/v2/resources/collection/monster-4.png
  src/v2/resources/collection/monster-5.png
  src/v2/resources/collection/popup.png
  src/v2/resources/collection/received.png
  src/v2/resources/collection/reward-bg.png
  src/v2/resources/collection/select-arrow.png
  src/v2/resources/collection/title.png
  src/v2/utils/staking.ts
  src/v2/utils/useBalance.ts
  src/v2/utils/useTx.ts
  src/v2/views/ClaimCollectionRewardsOverlay/ClaimContent.tsx
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/base.tsx
  src/v2/views/MonsterCollectionOverlay/dialog.stories.tsx
  src/v2/views/MonsterCollectionOverlay/dialog.tsx
  src/v2/views/MonsterCollectionOverlay/index.stories.tsx
  src/v2/views/MonsterCollectionOverlay/index.tsx
  src/v2/views/MonsterCollectionOverlay/level.tsx
  src/v2/views/MonsterCollectionOverlay/reward.tsx
  yarn.lock
Labels: Extra Large

#1435 Fix blank page shown when no stakeState presents
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1437 Correct `schema.graphql`
  src/schema.graphql
Labels: Extra Small

#1439 Prevent staking more than current NCG
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/dialog.tsx
Labels: Extra Small

#1441 Use normal weight on reward titles
  src/v2/views/MonsterCollectionOverlay/reward.tsx
Labels: Extra Small

#1440 Add a table of itemId and item information
  src/v2/resources/collection/items/400000.png
  src/v2/resources/collection/items/500000.png
  src/v2/utils/monsterCollection/items.ts
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1443 Refetch current after changed amount
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: Extra Small

#1444 Merge 2022q2 to previewnet
  src/schema.graphql
  src/v2/resources/collection/items/400000.png
  src/v2/resources/collection/items/500000.png
  src/v2/utils/monsterCollection/items.ts
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/dialog.tsx
  src/v2/views/MonsterCollectionOverlay/index.tsx
  src/v2/views/MonsterCollectionOverlay/reward.tsx
Labels: Small

#1442 Change staking menu item to newer staking
  src/v2/components/core/Menu/index.tsx
Labels: Extra Small

#1448 Remove zero-level from list
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1449 Fix command to staking
  src/main/headless/action.ts
  src/main/headless/headless.ts
  src/v2/utils/useTx.ts
Labels: Extra Small

#1450 Improve refetching logic on staking
  src/v2/components/core/Layout/UserInfo/index.tsx
  src/v2/utils/staking.ts
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: Extra Small

#1451 Disallow changing deposit on lockup
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/base.tsx
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: Extra Small

#1458 Fix the condition of canClaim
  src/v2/utils/staking.ts
Labels: Extra Small

#1459 Allow staking more while staking is uncancellable
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1460 Strip decimal point if it's irrelevant
  src/v2/components/core/Layout/UserInfo/index.tsx
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1452 Introduce `migrate-monster-collection` command
  src/main/headless/action.ts
  src/main/headless/headless.ts
Labels: Extra Small

#1461 Fix remaining decimal points on collection
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: No Changes

#1464 Calculate by sum of current balance and staked
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1466 Fix selectedIndex deps
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: No Changes

#1467 Replace useTipSubscription with useGetTipQuery
  src/v2/components/core/Layout/InfoText.tsx
  src/v2/components/core/Layout/UserInfo/index.tsx
  src/v2/utils/staking.ts
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: Extra Small

#1468 Merge 2022q2 into previewnet
  src/main/headless/action.ts
  src/main/headless/headless.ts
  src/v2/components/core/Layout/InfoText.tsx
  src/v2/components/core/Layout/UserInfo/index.tsx
  src/v2/utils/staking.ts
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: Small

#1474 Log tx information when staged
  src/v2/utils/useTx.ts
Labels: Extra Small

#1476 Add alert to confim staking changes
  src/v2/utils/useEvent.ts
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Small

#1478 Add missing deps for txStatus check
  src/v2/components/core/Layout/UserInfo/index.tsx
Labels: No Changes
