Repository planetarium/9c-launcher, pull requests merged in 2022-11, with the labels that each got.

#1969 [Feature] Replace to remote config in initializeConfig
  src/config.ts
  src/main/main.ts
Labels: Extra Small

#1970 add unity sentry sample rate option on player
  src/interfaces/config.ts
  src/stores/game.ts
Labels: Extra Small

#1972 Apply Relative tip comparison and ClientCount-weighted RPC Node Selector
  src/config.ts
  src/interfaces/config.ts
Labels: enhancement, Extra Small

#1975 Merge development into rc-v100320
  src/config.ts
  src/interfaces/config.ts
Labels: Extra Small

#1977 Remove @BasixKOR from auto_assign
  .github/auto_assign.yml
Labels: Extra Small

#1991 chore: Update download url
  .circleci/config.yml
  CONTRIBUTING.ko.md
  CONTRIBUTING.md
  package.json
Labels: Extra Small

#1996 [Fix] Solve lockfile permission issue in macos
  src/main/update/update.ts
Labels: Extra Small

#1999 [Feature] Change config.json path when os is macos
  src/config.ts
  src/main/update/launcher-update.ts
Labels: Extra Small

#1998 Prevent unnecessary GQL query before login
  src/v2/utils/useTx.ts
Labels: Extra Small

#2003 Add 'ClaimStakeReward' action's used block index as argument
  src/main/headless/action.ts
  src/main/headless/headless.ts
  src/v2/components/core/Layout/UserInfo/index.tsx
Labels: enhancement, Extra Small

#2007 Remove Aws Related Arguments
  src/interfaces/config.ts
  src/main/main.ts
Labels: Extra Small

#2008 Use "Activation Code" instead of "Invitation Code"
  src/interfaces/config.ts
  src/renderer/components/RetypePasswordForm.tsx
  src/renderer/views/lobby/LobbyView.tsx
  src/v2/components/RetypePasswordForm.tsx
  src/v2/components/ui/Link.tsx
  src/v2/views/MissingActivationView.tsx
  src/v2/views/RegisterView/index.tsx
Labels: Extra Small

#2014 Fix claim stake reward not working.
  src/main/headless/action.ts
Labels: bug, Extra Small

#2013 [Fix] update required rule
  src/main/update/check.ts
Labels: Extra Small

#2015 [Fix] Updaterequied rule
  src/main/update/check.ts
Labels: Extra Small
