Repository planetarium/9c-launcher, pull requests merged in 2022-07, with the labels that each got.

#1664 Move macOS/Linux build to Circle CI
  .circleci/config.yml
  .github/workflows/build.yml
  scripts/make-apv.sh
  scripts/sign-apv.sh
Labels: ci, Medium

#1681 Cache built submodule in CI
  .circleci/config.yml
  test
Labels: ci

#1689 Translated launcher comments
  scripts/configureApv.ts
  scripts/downloadPlayer.ts
  scripts/latestApvNo.ts
  scripts/packager.js
  src/config.ts
  src/main/main.ts
  src/main/update.ts
  src/renderer/DifferentAppProtocolVersionSubscriptionProvider.tsx
  src/renderer/views/lobby/LobbyView.tsx
  src/renderer/views/login/LoginView.tsx
  src/renderer/views/update/UpdateView.tsx
  src/v2/views/LoginView/index.tsx
Labels: documentation

#1591 Replace collection assets
  src/global.d.ts
  src/v2/resources/collection/bg.png
  src/v2/resources/collection/current-status-leaf.gif
  src/v2/resources/collection/current-status-leaf.png
  src/v2/resources/collection/item-bg.png
  src/v2/resources/collection/monster-3.png
  src/v2/resources/collection/select-arrow.gif
  src/v2/resources/collection/select-arrow.png
  src/v2/resources/collection/title.png
  src/v2/views/MonsterCollectionOverlay/level.tsx
  webpack.config.js
Labels: Extra Small

#1618 Center reward item frame on collection
  src/v2/views/MonsterCollectionOverlay/reward.tsx
Labels: Extra Small

#1670 The Great Electron Bump
  .yarnrc.yml
  __tests__/fixture/config.json
  __tests__/main.spec.ts
  package.json
  src/collection/App.tsx
  src/collection/window/index.ts
  src/config.ts
  src/main/headless/headless.ts
  src/main/headless/remoteHeadless.ts
  src/main/main.ts
  src/main/v2/application.ts
  src/preload/sentry.ts
  src/renderer/App.tsx
  src/renderer/components/ClearCacheButton.tsx
  src/renderer/i18n/index.tsx
  src/renderer/render.tsx
  src/renderer/views/config/ConfigurationView.tsx
  src/renderer/views/error/ErrorClearCacheView.tsx
  src/renderer/views/error/ErrorDownloadBinaryFailedView.tsx
  src/renderer/views/error/ErrorDownloadSnapshotFailedView.tsx
  src/renderer/views/error/ErrorDownloadSnapshotMetadataFailedView.tsx
  src/renderer/views/error/ErrorReinstallView.tsx
  src/renderer/views/error/ErrorRelaunchView.tsx
  src/transfer/window/index.ts
  src/v2/components/core/Layout/StatusBar.tsx
  src/v2/components/core/Layout/WindowControls.tsx
  src/v2/components/core/Menu/index.tsx
  src/v2/machines/preloadMachine.ts
  src/v2/render.tsx
  src/v2/utils/apolloClient.ts
  src/v2/views/ErrorView/index.tsx
  src/v2/views/LoginView/index.tsx
  src/v2/views/SettingsOverlay/FolderChooser.tsx
  src/v2/views/SettingsOverlay/index.tsx
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: Large
