Repository planetarium/9c-launcher, pull requests merged in 2022-06, with the labels that each got.

#1481 Track when launcher launches
  src/main/main.ts
  src/renderer/App.tsx
Labels: Extra Small

#1482 Add query to fetch genesis hash
  src/api.graphql
  src/main/headless/headless.ts
  src/renderer/App.tsx
  src/v2/utils/apolloClient.ts
Labels: Extra Small

#1488 Indicate insufficient funds when changing staking amount
  src/v2/components/ui/BareInput.tsx
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1489 Add CloseButton to collection
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/index.stories.tsx
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: Extra Small

#1487 Disable level if amount is insufficient
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/level.tsx
Labels: Extra Small

#1490 Add deposit days to collection
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1492 Update auto_assign list
  .github/auto_assign.yml
Labels: Extra Small

#1497 Import V1 GraphQL generated code instead of V2
  src/renderer/App.tsx
Labels: Extra Small

#1501 Implement basic migration UI
  package.json
  src/v2/resources/collection/popup-m.png
  src/v2/views/MonsterCollectionOverlay/dialog.stories.tsx
  src/v2/views/MonsterCollectionOverlay/dialog.tsx
  yarn.lock
Labels: Medium

#1509 Hide remaining days if it's claimable
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1508 Add onClose handler to Migration
  src/v2/views/MonsterCollectionOverlay/Migration.tsx
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: Extra Small

#1512 Update GraphQL on stakeRewards
  src/api.graphql
  src/schema.graphql
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/index.stories.tsx
Labels: Extra Large

#1518 Change zIndex of OverlayBase
  src/v2/components/core/OverlayBase/index.tsx
Labels: Extra Small

#1520 Change amount when an item got clicked
  src/v2/components/ui/BareInput.tsx
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/level.tsx
Labels: Extra Small

#1519 Add unclaimed alert
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/v2/views/MonsterCollectionOverlay/index.stories.tsx
Labels: Extra Small

#1528 Fix bonusRewardMap deps
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1530 Change the description of migration item
  src/v2/views/MonsterCollectionOverlay/Migration.tsx
Labels: Extra Small

#1529 Don't show toast when mining is disabled
  src/v2/views/LoginView/index.tsx
  src/v2/views/SettingsOverlay/index.tsx
Labels: Extra Small

#1533 Log out GraphQL errors
  src/v2/utils/apolloClient.ts
Labels: Extra Small

#1537 Apply zIndex to specific overlay only
  src/v2/components/core/OverlayBase/index.tsx
  src/v2/views/ClaimCollectionRewardsOverlay/ClaimContent.tsx
Labels: Extra Small

#1535 Prevent staking less than minimum amount
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1541 Track staking events on Mixpanel
  src/v2/components/core/Layout/UserInfo/index.tsx
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: Extra Small

#1550 Make Staking/ChangeAmount more resilient
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: Extra Small

#1551 Skip query if not logged in
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: Extra Small

#1552 Merge `rc-v100221` to `main`
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: bug

#1553 Merge `development` to `main`
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: Extra Small

#1555 Pad private key when passing it to the headless
  src/v2/views/LoginView/index.tsx
Labels: Extra Small

#1554 Correct monster collection deposit
  src/v2/views/MonsterCollectionOverlay/Migration.tsx
Labels: bug, Extra Small

#1562 Merge `rc-v100222` to `main`
  src/v2/views/LoginView/index.tsx
  src/v2/views/MonsterCollectionOverlay/Migration.tsx
Labels: Extra Small

#1567 Setup .NET SDK on macOS build
  .github/workflows/build.yml
Labels: Extra Small

#1568 Remove outlines on staking
  src/v2/views/MonsterCollectionOverlay/base.tsx
Labels: Extra Small

#1558 System Rewards on Collection
  src/v2/resources/collection/icon-action-power.png
  src/v2/resources/collection/icon-arena-reward.png
  src/v2/resources/collection/icon-crafting-slot.png
  src/v2/resources/collection/icon-grinding-crystal.png
  src/v2/utils/monsterCollection/systemRewards.ts
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1313 Add Yarn 3
  .circleci/config.yml
  .github/workflows/build.yml
  .gitignore
  .yarn/plugins/@yarnpkg/plugin-typescript.cjs
  .yarn/releases/yarn-3.2.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: Small

#1566 Applying Lint Globally
  .eslintrc
  package.json
  src/api.graphql
  src/collection.html
  src/collection/App.scss
  src/collection/App.tsx
  src/collection/common/styles/Typography.scss
  src/collection/components/Button/Button.scss
  src/collection/components/Cart/Cart.scss
  src/collection/components/Cart/CartItem/CartItem.scss
  src/collection/components/CollectionItem/CollectionItem.scss
  src/collection/components/CollectionPanel/CollectionPanel.scss
  src/collection/components/ExpectedStatusBoard/ExpectedStatusBoard.scss
  src/collection/components/ExpectedStatusBoard/RewardItem/RewardItem.scss
  src/collection/components/LoadingDialog/LoadingDialog.scss
  src/collection/components/RemainingDisplay/RemainingDisplay.scss
  src/collection/components/RenewDialog/RenewDialog.scss
  src/collection/components/Title/Title.scss
  src/collection/components/common/collectionSheet.ts
  src/collection/pages/landing/landing.scss
  src/collection/pages/main/loading.scss
  src/collection/pages/main/main.scss
  src/collection/pages/main/main.stories.tsx
  src/collection/pages/main/main.tsx
  src/config.ts
  src/hooks/useInterval.ts
  src/index.html
  src/main/headless/headless.ts
  src/main/headless/remoteHeadless.ts
  src/main/main.ts
  src/main/monosnapshot.ts
  src/main/snapshot.ts
  src/renderer/components/AccountInfo/AccountInfo.scss
  src/renderer/components/ClaimCollectionRewardDialog/ClaimCollectionRewardDialog.tsx
  src/renderer/components/ClaimCollectionRewardDialog/RewardItem/RewardItemComponent.scss
  src/renderer/styles/common.scss
  src/renderer/styles/layout/layout.scss
  src/renderer/views/lobby/LobbyView.tsx
  src/renderer/views/update/UpdateView.tsx
  src/transfer/App.scss
  src/transfer/stores/headless.ts
  src/v2.html
  src/v2/components/core/Layout/WindowControls.tsx
  src/v2/components/core/Menu/MenuItem.tsx
  src/v2/components/core/Menu/index.tsx
  src/v2/utils/monsterCollection/items.ts
  src/v2/views/ErrorView/index.tsx
  src/v2/views/MonsterCollectionOverlay/Migration.tsx
  src/v2/views/MonsterCollectionOverlay/index.stories.tsx
  src/v2/views/SettingsOverlay/FolderChooser.tsx
  src/v2/views/SettingsOverlay/index.tsx
  yarn.lock
Labels: Extra Large

#1173 Initialize Refiner
  package.json
  src/refiner.d.ts
  src/renderer/App.tsx
  src/renderer/views/login/LoginView.tsx
  src/v2/global.scss
  src/v2/render.tsx
  src/v2/views/LoginView/index.tsx
  yarn.lock
Labels: Small

#1590 Initialize refiner at login
  src/renderer/App.tsx
  src/renderer/views/login/LoginView.tsx
  src/v2/render.tsx
  src/v2/views/LoginView/index.tsx
Labels: Extra Small

#1536 Add useTip hook
  src/v2/components/core/Layout/InfoText.tsx
  src/v2/utils/staking.ts
  src/v2/utils/useTip.ts
  src/v2/views/MonsterCollectionOverlay/index.tsx
Labels: Small

#1573 Prevent depositing same amount as before
  src/v2/utils/useTx.ts
  src/v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#1605 Change amount of system rewards
  src/v2/utils/monsterCollection/systemRewards.ts
Labels: Extra Small

#1611 Use Yarn 3 cache on macOS CI
  .github/workflows/build.yml
Labels: Extra Small

#1598 Support Linux
  .github/workflows/build.yml
  package.json
  scripts/build-headless-linux.sh
  scripts/downloadPlayer.ts
  scripts/make-apv.ps1
  scripts/make-apv.sh
  src/main/main.ts
Labels: enhancement, Small

#1616 Enable Linux Build
  .github/workflows/build.yml
  package.json
  scripts/downloadPlayer.ts
  src/config.ts
Labels: Extra Small
