Repository planetarium/9c-launcher, pull requests merged in 2022-12, with the labels that each got.

#2018 Add '--block-index' Option Flag
  src/main/headless/action.ts
Labels: bug, Extra Small

#2022 Release v100330-3
  src/main/headless/action.ts
Labels: bug, Extra Small

#2030 Replaced APV Related headless feature
  package.json
  src/api.graphql
  src/config.ts
  src/interfaces/apv.ts
  src/main/headless/apv.ts
  src/main/headless/headless.ts
  src/main/headless/remoteHeadless.ts
  src/main/main.ts
  src/main/update/check.ts
  src/utils/apv.ts
  src/utils/bencodex.ts
  src/utils/graphql.ts
  src/utils/url.ts
  yarn.lock
Labels: enhancement, Large, separation

#2043 development to rc-100350-1
  __tests__/snapshot.spec.ts
Labels: Extra Small

#2033 Deprecate Keystore related Headless API
  __tests__/main/headless/validation.spec.ts
  package.json
  src/api.graphql
  src/interfaces/keystore.ts
  src/main/headless/headless.ts
  src/main/headless/key-store.ts
  src/main/headless/validation.ts
  src/main/main.ts
  src/renderer/IntroView.tsx
  src/renderer/views/account/CreateAccountView.tsx
  src/renderer/views/account/RevokeAccountView.tsx
  src/renderer/views/lobby/LobbyView.tsx
  src/renderer/views/login/LoginView.tsx
  src/renderer/views/main/MainView.tsx
  src/stores/account.ts
  src/v2/Routes.tsx
  src/v2/components/core/Layout/InfoText.tsx
  src/v2/components/core/Layout/StatusBar.tsx
  src/v2/components/core/Layout/UserInfo/index.tsx
  src/v2/components/core/Menu/index.tsx
  src/v2/utils/monsterCollection/index.ts
  src/v2/utils/staking.ts
  src/v2/utils/useActivation.ts
  src/v2/utils/useBalance.ts
  src/v2/utils/usePreload.ts
  src/v2/utils/useStore.tsx
  src/v2/utils/useTx.ts
  src/v2/views/ClaimCollectionRewardsOverlay/index.tsx
  src/v2/views/ForgotPasswordView/index.tsx
  src/v2/views/ImportView/index.tsx
  src/v2/views/LobbyView/index.tsx
  src/v2/views/LoginView/index.tsx
  src/v2/views/MonsterCollectionOverlay/index.tsx
  src/v2/views/RecoverView/index.tsx
  src/v2/views/RegisterView/index.tsx
  src/v2/views/RevokeView.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement, Extra Large, separation

#2050 Fixed errata
  src/v2/components/core/Layout/InfoText.tsx
Labels: Extra Small
