Repository planetarium/9c-launcher, pull requests merged in 2022-03, with the labels that each got.

#1237 Change label of ImportInput text field
  src/v2/components/ImportInput.tsx
Labels: v2

#1238 Improve validation of RetypePasswordForm
  src/v2/components/RetypePasswordForm.tsx
Labels: Extra Small, v2

#1246 Various V2 Monster Collection fixes
  src/v2/components/core/Layout/UserInfo/ClaimButton.tsx
  src/v2/views/ClaimCollectionRewardsOverlay/ClaimContent.tsx
  src/v2/views/ClaimCollectionRewardsOverlay/index.tsx
Labels: Small, v2

#1247 Await for page load
  src/main/v2/application.ts
Labels: Extra Small, v2

#1249 Fix V2 Updates
  src/main/main.ts
  src/v2/machines/updateMachine.ts
  src/v2/utils/APVSubscriptionProvider.tsx
  src/v2/views/UpdateView/StatusBar.tsx
  src/v2/views/UpdateView/index.tsx
Labels: Small

#1255 Improve RPC UI
  src/v2/components/core/Layout/InfoText.tsx
  src/v2/views/SettingsOverlay/index.tsx
Labels: Extra Small, v2

#1258 Remove mention about key file
  src/v2/views/ImportView/index.tsx
Labels: Extra Small

#1261 Fix Setting to be clickable when RPC host is long
  src/renderer/views/layout/Layout.tsx
Labels: Extra Small

#1262 Add top banner
  src/renderer/components/TopBanner.tsx
  src/renderer/views/layout/Layout.tsx
Labels: Extra Small

#1264 Cherry pick #1261 on the PreviewNet
  src/renderer/views/layout/Layout.tsx
Labels: Extra Small

#1263 Update style of TopBanner
  src/renderer/components/TopBanner.tsx
  src/renderer/resources/noticeTest.png
Labels: Small

#1265 Fix null check on useMonsterCollection
  src/v2/utils/monsterCollection/index.ts
Labels: Extra Small

#1267 Implement clear cache
  src/v2/views/SettingsOverlay/index.tsx
Labels: Extra Small

#1269 Stop marking RPC as an experimental feature
  src/renderer/views/config/ConfigurationView.tsx
Labels: Extra Small

#1278 Expose V2 interface option
  src/renderer/views/config/ConfigurationView.tsx
Labels: Extra Small

#1279 Disable OnboardingOverlay for the time being
  src/v2/views/LobbyView/index.tsx
Labels: Extra Small

#1274 Move download folder into BlockchainStoreDirParent
  package.json
  src/main/main.ts
  src/main/snapshot.ts
  yarn.lock
Labels: Extra Small

#1292 Bump Transifex SDK
  package.json
  src/renderer/i18n/index.tsx
  src/renderer/views/account/RevokeAccountView.tsx
  src/renderer/views/error/ErrorRelaunchView.tsx
  src/renderer/views/lobby/PreloadView.tsx
  src/renderer/views/login/MiningView.tsx
  src/renderer/views/preload/PreloadProgressView.tsx
  src/v2/views/RevokeView.tsx
  yarn.lock
Labels: Small

#1293 See tree hashes to check submodules
  .circleci/config.yml
  .github/workflows/build.yml
  scripts/check-submodules.sh
  scripts/checkSubmodule.ts
Labels: Medium

#1297 Add block counter
  src/v2/components/core/Layout/StatusBar.tsx
  src/v2/utils/usePreload.ts
  src/v2/views/LobbyView/index.tsx
Labels: Extra Small
