Repository planetarium/9c-launcher, pull requests merged in 2023-06, with the labels that each got.

#2176 Fix/swap rate text
  src/renderer/views/TransferAssetOverlay/swap.tsx
Labels: Extra Small

#2177 fix: Cache keynotfound error
  .github/workflows/build.yml
  .github/workflows/release.yml
  electron-builder.main.yml
Labels: Extra Small

#2178 ci: Cleanup unpacked dir
  .github/workflows/release.yml
Labels: Extra Small

#2192 remove unnessary rpm install
  .github/workflows/release.yml
Labels: ci

#2196 Exclude deb,rpm,pacman from action temporarily
  .github/workflows/release.yml
  electron-builder.main.yml
Labels: ci, Extra Small

#2197 0.2 to main (4th try)
  .github/workflows/build.yml
  .github/workflows/release.yml
  electron-builder.main.yml
Labels: ci, Extra Small

#2205 Update GQL Schema & Remove Unused Subscription API/Hooks
  src/api.graphql
  src/schema.graphql
  src/utils/monsterCollection/index.ts
Labels: enhancement, Extra Large

#2200 Implemented New Mead-Portal Activation Flow without Activation Code
  .github/workflows/build.yml
  src/api.graphql
  src/interfaces/activation.ts
  src/renderer/Routes.tsx
  src/renderer/components/ActivationKeyForm.tsx
  src/renderer/components/RetypePasswordForm.tsx
  src/renderer/components/core/Layout/StatusBar.tsx
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/components/core/Menu/index.tsx
  src/renderer/views/ConfirmUpdateView/index.tsx
  src/renderer/views/ErrorView/ErrorContent.tsx
  src/renderer/views/LobbyView/index.tsx
  src/renderer/views/RegisterView/ActivationKeyView.tsx
  src/renderer/views/RegisterView/CreateKeyView.tsx
  src/renderer/views/RegisterView/GetPatronView.tsx
  src/renderer/views/RegisterView/PledgeFailView.tsx
  src/renderer/views/RegisterView/PledgeSuccessView.tsx
  src/renderer/views/RegisterView/PledgeWaitView.tsx
  src/renderer/views/RegisterView/index.tsx
  src/schema.graphql
  src/stores/account.ts
  src/utils/useActivate.ts
  src/utils/useActivationStatus.ts
  src/utils/useCheckContract.ts
  src/utils/useExternalURL.tsx
  src/utils/usePledge.ts
Labels: enhancement, Extra Large

#2209 Cleaning config.json / re-link mead related URL
  __tests__/mock/MockNineChroniclesMixpanel.ts
  src/api.graphql
  src/config.ts
  src/interfaces/config.ts
  src/main/main.ts
  src/main/mixpanel.ts
  src/main/update/updater.ts
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/views/ErrorView/index.tsx
  src/renderer/views/LoginView/index.tsx
  src/renderer/views/MonsterCollectionOverlay/index.tsx
  src/renderer/views/RegisterView/CreateKeyView.tsx
  src/renderer/views/RegisterView/GetPatronView.tsx
  src/renderer/views/RegisterView/PledgeSuccessView.tsx
  src/renderer/views/RegisterView/PledgeWaitView.tsx
  src/renderer/views/SettingsOverlay/index.tsx
  src/renderer/views/TransferAssetOverlay/swap.tsx
  src/renderer/views/TransferAssetOverlay/transfer.tsx
  src/stores/game.ts
  src/utils/mixpanel.ts
  src/utils/transfer/utils.ts
  src/utils/usePledge.ts
Labels: bug, enhancement, Large

#2210 Version Update
  package.json
Labels: ci, Extra Small

#2203 Add Keystore Datamatrix Print Overlay (Export)
  bitgener.d.ts
  package.json
  src/renderer/components/core/Layout/UserInfo/ExportOverlay.tsx
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/stores/account.ts
  yarn.lock
Labels: enhancement, Medium

#2212 Set timeout to 2 minutes
  src/utils/usePledge.ts
Labels: bug

#2216 Export keystore in settings
  src/renderer/views/SettingsOverlay/index.tsx
Labels: Large

#2215 Hotfixes for v200030 RC1
  .github/workflows/release.yml
  bitgener.d.ts
  electron-builder.internal.yml
  electron-builder.local.yml
  electron-builder.main.yml
  package.json
  src/renderer/components/core/Layout/StatusBar.tsx
  src/renderer/components/core/Layout/UserInfo/ExportOverlay.tsx
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/views/SettingsOverlay/index.tsx
  src/stores/account.ts
  src/utils/usePledge.ts
  yarn.lock
Labels: bug, enhancement, ci, Large

#2218 Enhance update logic with version check defense
  .github/workflows/build.yml
  src/main/update/updater.ts
Labels: Extra Small

#2219 Change updater log level
  src/main/update/updater.ts
Labels: Extra Small

#2220 fix: Remove player update try-catch
  src/main/update/player-update.ts
Labels: Extra Small

#2221 fix: Disable autoInstallOnAppQuit
  src/main/update/updater.ts
Labels: Extra Small

#2222 Initial Vesioning Start (2.0.0)
  package.json
Labels: Extra Small, v2

#2223 Backmerging release branch to main
  .github/workflows/build.yml
  .github/workflows/release.yml
  bitgener.d.ts
  electron-builder.internal.yml
  electron-builder.local.yml
  electron-builder.main.yml
  package.json
  src/api.graphql
  src/interfaces/activation.ts
  src/main/update/player-update.ts
  src/main/update/updater.ts
  src/renderer/Routes.tsx
  src/renderer/components/ActivationKeyForm.tsx
  src/renderer/components/RetypePasswordForm.tsx
  src/renderer/components/core/Layout/StatusBar.tsx
  src/renderer/components/core/Layout/UserInfo/ExportOverlay.tsx
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/components/core/Menu/index.tsx
  src/renderer/views/ConfirmUpdateView/index.tsx
  src/renderer/views/ErrorView/ErrorContent.tsx
  src/renderer/views/LobbyView/index.tsx
  src/renderer/views/RegisterView/ActivationKeyView.tsx
  src/renderer/views/RegisterView/CreateKeyView.tsx
  src/renderer/views/RegisterView/GetPatronView.tsx
  src/renderer/views/RegisterView/PledgeFailView.tsx
  src/renderer/views/RegisterView/PledgeSuccessView.tsx
  src/renderer/views/RegisterView/PledgeWaitView.tsx
  src/renderer/views/RegisterView/index.tsx
  src/renderer/views/SettingsOverlay/index.tsx
  src/schema.graphql
  src/stores/account.ts
  src/utils/monsterCollection/index.ts
  src/utils/useActivate.ts
  src/utils/useActivationStatus.ts
  src/utils/useCheckContract.ts
  src/utils/useExternalURL.tsx
  src/utils/usePledge.ts
  yarn.lock
Labels: ci, Extra Large

#2224 Backmerging release branch to development
  .github/workflows/build.yml
  .github/workflows/release.yml
  bitgener.d.ts
  electron-builder.internal.yml
  electron-builder.local.yml
  electron-builder.main.yml
  package.json
  src/api.graphql
  src/main/update/player-update.ts
  src/main/update/updater.ts
  src/renderer/components/core/Layout/StatusBar.tsx
  src/renderer/components/core/Layout/UserInfo/ExportOverlay.tsx
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/views/SettingsOverlay/index.tsx
  src/schema.graphql
  src/stores/account.ts
  src/utils/usePledge.ts
  yarn.lock
Labels: ci, Large

#2225 Release 2.0.0 to main
  src/main/update/updater.ts
Labels: Extra Small

#2226 Release 2.0.0 to development
  src/main/update/updater.ts
Labels: Extra Small

#2227 [TEMP FIX] Filter all reward with CURRENCY Type
  src/api.graphql
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/index.stories.tsx
Labels: bug, Extra Small

#2217 [Feature] Introduce apple code signing and notarization
  .github/workflows/build.yml
  .github/workflows/release.yml
  electron-builder.internal.yml
  electron-builder.main.yml
  package.json
  scripts/release.sh
  signing/entitlements.inherit.plist
  signing/entitlements.plist
  yarn.lock
Labels: Small

#2229 Use first two part of version from original package.json
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: ci, Extra Small
