Repository planetarium/9c-launcher, pull requests merged in 2023-01, with the labels that each got.

#2062 Fix routing error on there's no key in keystore.
  package.json
  src/renderer/Routes.tsx
  src/stores/account.ts
  src/stores/transfer.ts
  yarn.lock
Labels: bug, Extra Small, headless-less

#2063 Fix False Timeout on Send NCG
  codegen.yml
  src/mappers.ts
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/index.tsx
  src/renderer/views/TransferAssetOverlay/swap.tsx
  src/renderer/views/TransferAssetOverlay/transfer.tsx
  src/stores/transfer.ts
Labels: bug, Extra Small, headless-less

#2064 [Feature] Remove usePreload
  src/renderer/components/core/Layout/StatusBar.tsx
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/views/LobbyView/index.tsx
  src/stores/game.ts
  src/utils/useActivation.ts
  src/utils/useIsHeadlessAvailable.ts
  src/utils/usePreload.ts
Labels: Medium

#2066 Remove obsolete configurations from Settings View
  src/renderer/views/SettingsOverlay/index.tsx
Labels: Extra Small, headless-less

#2068 Fix input field overflow on over 6 digits on StakingView
  src/index.html
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/base.tsx
  src/renderer/views/MonsterCollectionOverlay/reward.tsx
Labels: bug, Extra Small

#2069 Fix last used address selected
  src/renderer/views/LoginView/index.tsx
Labels: bug, Extra Small

#2070 Fix preemptive error throwing before ActionTxQuery done
  src/renderer/views/MonsterCollectionOverlay/index.tsx
Labels: bug, Extra Small

#2071 Temporary Solution for PrivateKey.
  src/renderer/components/core/Layout/StatusBar.tsx
  src/renderer/views/LobbyView/index.tsx
  src/stores/account.ts
Labels: invalid, Extra Small

#2072 Monkey Spanner Fix for account-local applied
  package.json
  yarn.lock
Labels: invalid, Extra Small

#2074 [Fix] Adjust `encounter different version` event APV values
  src/api.graphql
  src/main/main.ts
  src/utils/apv.ts
Labels: Extra Small

#2078 Fix/version display
  src/utils/apv.ts
Labels: Extra Small

#2079 MonsterCollection Amount Invalidation & More Logical Input Field
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: bug, Extra Small

#2080 Add proper input validation in forgot password view
  src/renderer/views/ForgotPasswordView/index.tsx
Labels: bug, Extra Small

#2077 Fix account related bugs
  .circleci/config.yml
  package.json
  src/renderer/components/core/Layout/InfoText.tsx
  src/renderer/components/core/Layout/StatusBar.tsx
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/views/ClaimCollectionRewardsOverlay/index.tsx
  src/renderer/views/ForgotPasswordView/index.tsx
  src/renderer/views/ImportView/index.tsx
  src/renderer/views/LobbyView/index.tsx
  src/renderer/views/LoginView/index.tsx
  src/renderer/views/MissingActivationView.tsx
  src/renderer/views/MonsterCollectionOverlay/Migration.tsx
  src/renderer/views/MonsterCollectionOverlay/index.tsx
  src/renderer/views/RecoverView/index.tsx
  src/renderer/views/RegisterView/index.tsx
  src/renderer/views/RevokeView.tsx
  src/renderer/views/TransferAssetOverlay/swap.tsx
  src/renderer/views/TransferAssetOverlay/transfer.tsx
  src/stores/account.ts
  src/utils/monsterCollection/index.ts
  src/utils/staking.ts
  src/utils/useActivation.ts
  src/utils/useBalance.ts
  src/utils/useLoginSession.ts
  src/utils/useTx.ts
  yarn.lock
Labels: Extra Large

#2081 Fix Keystore Duplication - Improper Key Handling while forgot password process
  src/renderer/components/RetypePasswordForm.tsx
  src/renderer/views/RecoverView/index.tsx
  src/renderer/views/RegisterView/index.tsx
  src/stores/account.ts
Labels: bug, Extra Small

#2082 Fixed start button enabled on improper context after recover password
  src/renderer/views/RecoverView/index.tsx
  src/utils/useActivation.ts
Labels: bug, Extra Small
