Repository planetarium/9c-launcher, pull requests merged in 2023-09, with the labels that each got.

#2300 release/2.3.6 to main
  .github/workflows/build.yml
  .github/workflows/release.yml
  electron-builder.main.yml
  package.json
  src/config.ts
  src/interfaces/config.ts
  src/main/main.ts
  src/main/update/player-update.ts
  src/main/update/updater.ts
  src/utils.ts
Labels: dependencies, Medium

#2301 Release/2.3.6 to development
  .github/workflows/release.yml
  package.json
  src/config.ts
  src/interfaces/config.ts
  src/main/main.ts
  src/main/update/player-update.ts
  src/utils.ts
Labels: dependencies, Medium

#2206 General... Dependancy Version Updating... and Cleaning...
  .eslintrc
  .github/workflows/build.yml
  .github/workflows/release.yml
  package.json
  sentry-symbols.js
  src/main/main.ts
  src/renderer/components/core/Layout/WindowControls.tsx
  src/renderer/render.tsx
  src/renderer/views/MonsterCollectionOverlay/dialog.stories.tsx
  src/renderer/views/MonsterCollectionOverlay/dialog.tsx
  src/renderer/views/SettingsOverlay/index.tsx
  src/stores/account.ts
  src/utils/apolloClient.ts
  src/utils/apv.ts
  src/utils/bencodex.ts
  src/utils/sentry.ts
  tsconfig.json
  webpack.config.ts
  yarn.lock
Labels: enhancement, Extra Large

#2304 Fix chromatic action
  .github/workflows/chromatic.yml
  .gitignore
  .gitmodules
  .storybook/main.js
  package.json
  tsconfig.json
  webpack.config.ts
  yarn.lock
Labels: Extra Small

#2303 Update Monster Collection UI and It's GQL API Usage
  .eslintrc
  package.json
  src/api.graphql
  src/renderer/.gitignore
  src/renderer/components/core/Layout/UserInfo/StakeStatus.tsx
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/views/MonsterCollectionOverlay/Migration.tsx
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/base.tsx
  src/renderer/views/MonsterCollectionOverlay/index.stories.tsx
  src/renderer/views/MonsterCollectionOverlay/index.tsx
  src/schema.graphql
  src/utils/staking.ts
  yarn.lock
Labels: enhancement, Extra Large

#2305 Use Official Chromatic Action
  .eslintrc
  .github/workflows/build.yml
  .github/workflows/chromatic.yml
  .github/workflows/styles.yml
  .github/workflows/translation.yml
  package.json
  src/api.graphql
  src/renderer/.gitignore
  src/renderer/components/core/Layout/UserInfo/StakeStatus.tsx
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/views/MonsterCollectionOverlay/Migration.tsx
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/base.tsx
  src/renderer/views/MonsterCollectionOverlay/index.stories.tsx
  src/renderer/views/MonsterCollectionOverlay/index.tsx
  src/schema.graphql
  src/utils/staking.ts
  yarn.lock
Labels: Extra Large

#2310 Remove Comments
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/index.tsx
Labels: bug, Extra Small

#2311 Fix Various problems related to stake state management
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/index.tsx
  src/renderer/views/MonsterCollectionOverlay/reward.tsx
  src/renderer/views/TransferAssetOverlay/swap.tsx
  src/renderer/views/TransferAssetOverlay/transfer.tsx
Labels: Small

#2316 Fix bunch of monster collection / user staking related state update issue
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/base.tsx
  src/renderer/views/MonsterCollectionOverlay/index.stories.tsx
  src/renderer/views/MonsterCollectionOverlay/index.tsx
Labels: bug, Medium

#2317 Correct recurring rewards calculation
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: bug, Extra Small

#2318 Don't update Available NCG after initial render
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: bug, Extra Small

#2324 Add patrol reward service url
  src/interfaces/config.ts
  src/stores/game.ts
Labels: Extra Small

#2323 Use the patronAddress from the pladge states
  src/api.graphql
  src/utils/usePledge.ts
Labels: Small

#2325 Add QR Hide Button
  package.json
  src/renderer/components/core/Layout/UserInfo/ExportOverlay.tsx
Labels: enhancement, Extra Small

#2326 Unset min-width on #2325....
  src/renderer/components/core/Layout/UserInfo/ExportOverlay.tsx
Labels: bug, Extra Small
