Repository planetarium/9c-launcher, pull requests merged in 2023-07, with the labels that each got.

#2230 [CI] separate github action os and runs on linux
  .github/workflows/build.yml
  .github/workflows/release.yml
  package.json
Labels: Extra Small

#2231 ci: separate linux release
  .github/workflows/release.yml
Labels: Extra Small

#2239 Backmerging Release/2.1.1
  package.json
Labels: Extra Small

#2241 Add UpdatedAddresses in transfer_asset
  package.json
  src/renderer/views/SettingsOverlay/index.tsx
  src/renderer/views/TransferAssetOverlay/swap.tsx
  src/stores/transfer.ts
  src/utils/sign.ts
  yarn.lock
Labels: bug, Small

#2243 Add UpdatedAddresses in transfer_asset
  package.json
  src/renderer/views/SettingsOverlay/index.tsx
  src/renderer/views/TransferAssetOverlay/swap.tsx
  src/stores/transfer.ts
  src/utils/sign.ts
  yarn.lock
Labels: bug, Small

#2244 Backmerging release/2.1.2
  .github/workflows/release.yml
  electron-builder.internal.yml
  electron-builder.main.yml
  package.json
Labels: Extra Small

#2247 Backmerging Release/2.1.2
  .github/workflows/build.yml
  .github/workflows/release.yml
  package.json
  scripts/release.sh
  signing/entitlements.inherit.plist
  signing/entitlements.plist
  src/api.graphql
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/index.stories.tsx
  src/renderer/views/SettingsOverlay/index.tsx
  src/renderer/views/TransferAssetOverlay/swap.tsx
  src/stores/transfer.ts
  src/utils/sign.ts
  webpack.config.js
  yarn.lock
Labels: ci, Large

#2251 Hotfix 2.1.3
  package.json
  src/main/main.ts
  src/utils/monsterCollection/removeSubscription.ts
  yarn.lock
Labels: Extra Small

#2252 Release/2.1.3 to development
  package.json
  src/main/main.ts
  src/utils/monsterCollection/removeSubscription.ts
Labels: Extra Small

#2253 Hotfix 2.1.4
  package.json
  src/main/main.ts
Labels: Extra Small

#2255 Release/2.1.4 to development
  package.json
  src/main/main.ts
Labels: Extra Small

#2257 hotfix 2.2.0
  package.json
Labels: Extra Small

#2258 Release/2.2.0 to development
  package.json
Labels: Extra Small

#2256 [CI] Rollback mac signing options
  .github/workflows/build.yml
  .github/workflows/release.yml
  electron-builder.internal.yml
  electron-builder.main.yml
  package.json
  yarn.lock
Labels: Small

#2260 Prevent Locale Value Overwrite
  src/main/main.ts
Labels: bug, Extra Small

#2262 Change Logo on WelcomeView
  src/renderer/resources/logo.png
  src/renderer/views/WelcomeView/index.tsx
Labels: Extra Small

#2248 Read APV From Remote Node, not config
  src/config.ts
  src/renderer/components/core/Layout/InfoText.tsx
Labels: bug, Extra Small, headless-less

#2261 Hide to tray on click X, quit on tray
  src/interfaces/config.ts
  src/main/application.ts
  src/main/main.ts
  src/renderer/views/SettingsOverlay/index.tsx
Labels: enhancement, Extra Small

#2263 Fix Manual Player Update
  src/main/main.ts
  src/renderer/views/SettingsOverlay/index.tsx
Labels: bug, Extra Small

#2264 Fix Text Break character escape
  src/renderer/i18n/index.tsx
  src/renderer/views/RegisterView/PledgeFailView.tsx
Labels: bug, Extra Small

#2265 Change Key Export Format DMX -> QR
  bitgener.d.ts
  package.json
  src/renderer/components/core/Layout/UserInfo/ExportOverlay.tsx
  yarn.lock
Labels: enhancement, Small

#2266 Disable Stake / Transfer On Not Pledged
  src/renderer/components/core/Menu/index.tsx
Labels: bug, Extra Small

#2267 feat: Upgrade apollo client version
  package.json
  src/main/main.ts
  yarn.lock
Labels: Extra Small

#2268 v2.3.0 Backmerge
  package.json
Labels: Extra Small

#2269 Backmerge Release/2.3.0 to main
  .github/workflows/build.yml
  .github/workflows/release.yml
  bitgener.d.ts
  electron-builder.internal.yml
  electron-builder.main.yml
  package.json
  src/config.ts
  src/interfaces/config.ts
  src/main/application.ts
  src/main/main.ts
  src/renderer/components/core/Layout/InfoText.tsx
  src/renderer/components/core/Layout/UserInfo/ExportOverlay.tsx
  src/renderer/components/core/Menu/index.tsx
  src/renderer/i18n/index.tsx
  src/renderer/resources/logo.png
  src/renderer/views/RegisterView/PledgeFailView.tsx
  src/renderer/views/SettingsOverlay/index.tsx
  src/renderer/views/WelcomeView/index.tsx
  yarn.lock
Labels: Large
