Repository planetarium/9c-launcher, pull requests merged in 2023-08, with the labels that each got.

#2270 Change Icon Resource
  AppIcon.icns
  app.ico
  src/renderer/resources/launcher-logo.png
Labels: enhancement, No Changes

#2271 Backmerging Release/2.3.0 to main again
  AppIcon.icns
  app.ico
  src/renderer/resources/launcher-logo.png
Labels: No Changes

#2272 Increase role duration seconds
  .github/workflows/release.yml
Labels: Extra Small

#2273 Change missing logo in main process
  src/main/resources/icon.ico
  src/main/resources/logo.png
Labels: bug, No Changes

#2275 Change missing logo in main process
  src/main/resources/icon.ico
  src/main/resources/logo.png
Labels: bug, duplicate, ci, No Changes

#2276 Backmerging Release/2.3.1 to main
  package.json
  src/main/resources/icon.ico
  src/main/resources/logo.png
Labels: ci, Extra Small

#2277 Backmerging Release/2.3.1 to development
  package.json
Labels: bug, ci

#2280 Display FAV in MonsterCollection Reward
  src/api.graphql
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/schema.graphql
  src/utils/monsterCollection/items.ts
Labels: enhancement, Large

#2283 Forced non-null assertion causing type error in runtime
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: bug

#2284 Fix type error on reward diff logic
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: bug, Extra Small

#2285 Merge "release/2.3.2" into "main"
  package.json
  src/api.graphql
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/schema.graphql
  src/utils/monsterCollection/items.ts
Labels: Large

#2286 Hotfix Release/2.3.3
  .github/workflows/release.yml
  package.json
Labels: Extra Small

#2288 Hotfix/2.3.5 to main
  package.json
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/components/core/Menu/index.tsx
Labels: bug, Extra Small

#2293 [CI] Restore mac, linux release and fix csc link
  .github/workflows/release.yml
Labels: Extra Small

#2294 [Feature] Silent update mode
  src/main/update/updater.ts
Labels: Extra Small

#2295 Fix release workflows
  .github/workflows/build.yml
  .github/workflows/release.yml
  electron-builder.main.yml
Labels: Extra Small

#2296 After force run option
  src/main/update/updater.ts
Labels: Extra Small

#2297 Add getExecutePath() to adapt legacy binary name
  package.json
  src/config.ts
  src/main/main.ts
  src/utils.ts
Labels: bug, Extra Small

#2298 Trigger manual player update if player binary not found at all
  src/main/main.ts
  src/utils.ts
Labels: bug

#2299 Add PlayerUpdateRetryCount in config.json and Prevent Infinite Restart
  src/interfaces/config.ts
  src/main/main.ts
  src/main/update/player-update.ts
Labels: Extra Small
