Repository planetarium/9c-launcher, pull requests merged in 2023-03, with the labels that each got.

#2109 merge rc-v100370-1 into main
  src/renderer/views/TransferAssetOverlay/main.tsx
  yarn.lock
Labels: Extra Small

#2112 Zero-pad on 'short-key' scenario and rewrite keyfile.
  package.json
  src/stores/account.ts
  src/utils/web3key.ts
  yarn.lock
Labels: enhancement, Medium

#2110 feat: Activation Flow Update
  src/api.graphql
  src/config.ts
  src/interfaces/activation.ts
  src/interfaces/config.ts
  src/renderer/components/ActivationKeyForm.tsx
  src/renderer/components/RetypePasswordForm.tsx
  src/renderer/components/core/Layout/StatusBar.tsx
  src/renderer/components/ui/Carousel.tsx
  src/renderer/components/ui/Link.tsx
  src/renderer/components/ui/Text.tsx
  src/renderer/views/LobbyView/index.tsx
  src/renderer/views/LoginView/index.tsx
  src/renderer/views/MissingActivationView.tsx
  src/renderer/views/OnboardingOverlay/index.tsx
  src/renderer/views/RegisterView/index.tsx
  src/renderer/views/RegisterView/subviews/ActivationKeySubview.tsx
  src/renderer/views/RegisterView/subviews/ActivationResultSubview.tsx
  src/renderer/views/RegisterView/subviews/ActivationWaitSubview.tsx
  src/renderer/views/RegisterView/subviews/CreateKeySubview.tsx
  src/renderer/views/RegisterView/subviews/index.ts
  src/renderer/views/WelcomeView/index.tsx
  src/utils/useActivate.ts
  src/utils/useActivation.ts
  src/utils/useActivationStatus.ts
Labels: Extra Large

#2113 chore: activation flow text update
  src/interfaces/config.ts
  src/renderer/views/RegisterView/subviews/ActivationWaitSubview.tsx
Labels: Extra Small

#2114 fix: activation flow
  src/renderer/Routes.tsx
  src/renderer/components/ActivationKeyForm.tsx
  src/renderer/components/RetypePasswordForm.tsx
  src/renderer/resources/icons/loading.png
  src/renderer/views/LobbyView/index.tsx
  src/renderer/views/MissingActivationView.tsx
  src/renderer/views/RegisterView/ActivationFailView.tsx
  src/renderer/views/RegisterView/ActivationKeyView.tsx
  src/renderer/views/RegisterView/ActivationSuccessView.tsx
  src/renderer/views/RegisterView/ActivationWaitView.tsx
  src/renderer/views/RegisterView/CreateKeyView.tsx
  src/renderer/views/RegisterView/index.tsx
  src/renderer/views/RegisterView/subviews/index.ts
  src/renderer/views/WelcomeView/index.tsx
Labels: Large

#2116 chore: update activation error text
  src/renderer/components/ActivationKeyForm.tsx
Labels: Extra Small

#2121 chore: add translation tags
  src/renderer/components/ActivationKeyForm.tsx
  src/renderer/components/RetypePasswordForm.tsx
  src/renderer/views/RegisterView/ActivationFailView.tsx
  src/renderer/views/RegisterView/ActivationKeyView.tsx
  src/renderer/views/RegisterView/ActivationSuccessView.tsx
  src/renderer/views/RegisterView/ActivationWaitView.tsx
  src/renderer/views/RegisterView/CreateKeyView.tsx
Labels: Medium

#2122 chore: add translation tags (#2121) to v100380
  src/renderer/components/ActivationKeyForm.tsx
  src/renderer/components/RetypePasswordForm.tsx
  src/renderer/views/RegisterView/ActivationFailView.tsx
  src/renderer/views/RegisterView/ActivationKeyView.tsx
  src/renderer/views/RegisterView/ActivationSuccessView.tsx
  src/renderer/views/RegisterView/ActivationWaitView.tsx
  src/renderer/views/RegisterView/CreateKeyView.tsx
Labels: Medium

#2124 merge rc-v100380-1 into development
  src/interfaces/config.ts
  src/stores/game.ts
Labels: Extra Small

#2123 merge rc-v100380-1 into main
  .github/auto_assign.yml
  README.md
  package.json
  src/api.graphql
  src/config.ts
  src/interfaces/activation.ts
  src/interfaces/config.ts
  src/renderer/Routes.tsx
  src/renderer/components/ActivationKeyForm.tsx
  src/renderer/components/RetypePasswordForm.tsx
  src/renderer/components/core/Layout/StatusBar.tsx
  src/renderer/components/ui/Carousel.tsx
  src/renderer/components/ui/Link.tsx
  src/renderer/components/ui/Text.tsx
  src/renderer/resources/icons/loading.png
  src/renderer/views/LobbyView/index.tsx
  src/renderer/views/LoginView/index.tsx
  src/renderer/views/MissingActivationView.tsx
  src/renderer/views/OnboardingOverlay/index.tsx
  src/renderer/views/RegisterView/ActivationFailView.tsx
  src/renderer/views/RegisterView/ActivationKeyView.tsx
  src/renderer/views/RegisterView/ActivationSuccessView.tsx
  src/renderer/views/RegisterView/ActivationWaitView.tsx
  src/renderer/views/RegisterView/CreateKeyView.tsx
  src/renderer/views/RegisterView/index.tsx
  src/renderer/views/WelcomeView/index.tsx
  src/stores/account.ts
  src/stores/game.ts
  src/utils/useActivate.ts
  src/utils/useActivation.ts
  src/utils/useActivationStatus.ts
  src/utils/web3key.ts
  yarn.lock
Labels: Extra Large
