Repository planetarium/9c-launcher, pull requests merged in 2024-03, with the labels that each got.

#2420 backmerge Release/2.5.9 to dev
  package.json
  src/renderer/resources/logo.png
  src/stores/game.ts
Labels: dependencies, Extra Small

#2422 Release/2.5.10
  package.json
  src/renderer/views/TransferAssetOverlay/transfer.tsx
  src/stores/planetary.ts
Labels: bug, Extra Small

#2426 Release/2.5.11
  package.json
  src/interfaces/config.ts
  src/renderer/views/TransferAssetOverlay/main.tsx
  yarn.lock
Labels: Extra Small

#2427 Backmerge Release/2.5.11 to dev
  package.json
  src/interfaces/config.ts
  src/renderer/views/TransferAssetOverlay/main.tsx
Labels: Extra Small

#2428 Add NCloud CDN Purge after release
  .github/workflows/release.yml
  scripts/purge-ncloud-cdn.sh
Labels: Extra Small

#2429 Run as bash & use gdate on macOS
  .github/workflows/release.yml
  scripts/purge-ncloud-cdn.sh
Labels: Extra Small

#2430 Feature/purge ncloud cdn
  .github/workflows/release.yml
  scripts/purge-ncloud-cdn.sh
Labels: Extra Small
