Repository planetarium/9c-launcher, pull requests merged in 2024-02, with the labels that each got.

#2411 Add maintenance flag for player
  src/interfaces/config.ts
  src/stores/game.ts
Labels: Extra Small

#2412 Add: new reward resource
  src/renderer/resources/collection/items/600202.png
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/utils/monsterCollection/items.ts
Labels: enhancement

#2413 Fix maintenance args
  src/stores/game.ts
Labels: bug, Extra Small

#2416 Release/2.5.9
  package.json
  src/interfaces/config.ts
  src/renderer/resources/collection/items/600202.png
  src/renderer/resources/logo.png
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/stores/game.ts
  src/utils/monsterCollection/items.ts
Labels: enhancement, Extra Small
