Repository planetarium/9c-launcher, pull requests merged in 2024-01, with the labels that each got.

#2397 Fix/monster collection revise
  src/renderer/resources/collection/items/800202.png
  src/renderer/resources/collection/items/garage.png
  src/renderer/resources/collection/items/ncg.png
  src/renderer/resources/collection/monster-3.png
  src/renderer/resources/collection/monster-4.png
  src/renderer/resources/collection/monster-5.png
  src/renderer/resources/collection/monster-6.png
  src/renderer/resources/collection/monster-7.png
  src/renderer/resources/collection/monster-8.png
  src/renderer/resources/ui-main-icon-gold.png
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/reward.tsx
  src/utils/monsterCollection/items.ts
Labels: enhancement

#2399 Release/2.5.4 to main.
  package.json
  src/config.ts
  src/main/exceptions/FetchError.ts
  src/main/exceptions/cancellable-download-failed.ts
  src/main/exceptions/cancellable-extract-failed.ts
  src/main/exceptions/clear-cache-exception.ts
  src/main/exceptions/download-snapshot-failed.ts
  src/main/exceptions/download-snapshot-metadata-failed.ts
  src/main/exceptions/extract-snapshot-failed.ts
  src/main/exceptions/index.ts
  src/renderer/resources/collection/items/800202.png
  src/renderer/resources/collection/items/garage.png
  src/renderer/resources/collection/items/ncg.png
  src/renderer/resources/collection/monster-3.png
  src/renderer/resources/collection/monster-4.png
  src/renderer/resources/collection/monster-5.png
  src/renderer/resources/collection/monster-6.png
  src/renderer/resources/collection/monster-7.png
  src/renderer/resources/collection/monster-8.png
  src/renderer/resources/ui-main-icon-gold.png
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/level.tsx
  src/renderer/views/MonsterCollectionOverlay/reward.tsx
  src/renderer/views/SettingsOverlay/index.tsx
  src/utils.ts
  src/utils/apolloClient.ts
  src/utils/monsterCollection/items.ts
  src/utils/monsterCollection/systemRewards.ts
  yarn.lock
Labels: ci, Large

#2398 add optional guild service args for player
  src/interfaces/config.ts
  src/stores/game.ts
Labels: Small

#2400 Backmerging Release/2.5.4 to development
  package.json
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/level.tsx
  src/utils/monsterCollection/systemRewards.ts
Labels: ci, Small

#2401 Release Hotfix/2.5.5: Revise Migration Warning
  package.json
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/dialog.tsx
Labels: enhancement, Extra Small

#2402 Hotfix/2.5.6 to main
  package.json
  src/renderer/views/SettingsOverlay/index.tsx
Labels: bug, ci, dependencies, Small

#2403 backmerging Hotfix/2.5.5 to dev
  package.json
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
  src/renderer/views/MonsterCollectionOverlay/dialog.tsx
Labels: Extra Small

#2404 Backmerging Hotfix/2.5.6 to dev
  package.json
  src/renderer/views/SettingsOverlay/index.tsx
Labels: Small

#2407 Hotfix 2.5.7 : Add Tip Pre-initialization check in Migration logic
  package.json
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: bug, ci, dependencies, Extra Small

#2408 development backmerge main 2.5.7
  package.json
  src/renderer/components/core/Layout/UserInfo/index.tsx
  src/renderer/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx
Labels: Extra Small

#2410 main merge release/2.5.8
  src/interfaces/config.ts
  src/interfaces/registry.ts
  src/main/main.ts
  src/stores/game.ts
  src/stores/planetary.ts
  yarn.lock
Labels: Small
